<?php
/**
 * InvoiceDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  d2r_connector\conficio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PartnerExchangeApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace d2r_connector\conficio;

use PHPUnit\Framework\TestCase;

/**
 * InvoiceDetailTest Class Doc Comment
 *
 * @category    Class
 * @description The invoice detail.
 * @package     d2r_connector\conficio
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InvoiceDetailTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceDetail"
     */
    public function testInvoiceDetail()
    {
    }

    /**
     * Test attribute "con_cap_pro_account_id"
     */
    public function testPropertyConCapProAccountId()
    {
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
    }

    /**
     * Test attribute "transaction_date"
     */
    public function testPropertyTransactionDate()
    {
    }

    /**
     * Test attribute "agency_transaction_id"
     */
    public function testPropertyAgencyTransactionId()
    {
    }

    /**
     * Test attribute "creditor_transaction_id"
     */
    public function testPropertyCreditorTransactionId()
    {
    }

    /**
     * Test attribute "posting_date"
     */
    public function testPropertyPostingDate()
    {
    }

    /**
     * Test attribute "transaction_code"
     */
    public function testPropertyTransactionCode()
    {
    }

    /**
     * Test attribute "transaction_amount"
     */
    public function testPropertyTransactionAmount()
    {
    }

    /**
     * Test attribute "commission_rate"
     */
    public function testPropertyCommissionRate()
    {
    }

    /**
     * Test attribute "commission"
     */
    public function testPropertyCommission()
    {
    }

    /**
     * Test attribute "amount_due_agency"
     */
    public function testPropertyAmountDueAgency()
    {
    }

    /**
     * Test attribute "amount_due_creditor"
     */
    public function testPropertyAmountDueCreditor()
    {
    }
}
