<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PartnerExchangeApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client;

use PHPUnit\Framework\TestCase;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class
 * @description The invoice.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InvoiceTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
    }

    /**
     * Test attribute "from"
     */
    public function testPropertyFrom()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "total_paid"
     */
    public function testPropertyTotalPaid()
    {
    }

    /**
     * Test attribute "total_commission"
     */
    public function testPropertyTotalCommission()
    {
    }

    /**
     * Test attribute "total_due_agency"
     */
    public function testPropertyTotalDueAgency()
    {
    }

    /**
     * Test attribute "total_due_creditor"
     */
    public function testPropertyTotalDueCreditor()
    {
    }

    /**
     * Test attribute "sales_tax1_name"
     */
    public function testPropertySalesTax1Name()
    {
    }

    /**
     * Test attribute "sales_tax1_amount"
     */
    public function testPropertySalesTax1Amount()
    {
    }

    /**
     * Test attribute "sales_tax2_name"
     */
    public function testPropertySalesTax2Name()
    {
    }

    /**
     * Test attribute "sales_tax2_amount"
     */
    public function testPropertySalesTax2Amount()
    {
    }

    /**
     * Test attribute "sales_tax3_name"
     */
    public function testPropertySalesTax3Name()
    {
    }

    /**
     * Test attribute "sales_tax3_amount"
     */
    public function testPropertySalesTax3Amount()
    {
    }

    /**
     * Test attribute "sales_tax_ids"
     */
    public function testPropertySalesTaxIds()
    {
    }

    /**
     * Test attribute "payment_to_agency"
     */
    public function testPropertyPaymentToAgency()
    {
    }

    /**
     * Test attribute "payment_to_creditor"
     */
    public function testPropertyPaymentToCreditor()
    {
    }
}
