<?php
/**
 * InvoiceDetailApiTest
 * PHP version 5
 *
 * @category Class
 * @package  d2r_connectors\conficio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PartnerExchangeApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace d2r_connectors\conficio;

use \d2r_connectors\conficio\Configuration;
use \d2r_connectors\conficio\ApiException;
use \d2r_connectors\conficio\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoiceDetailApiTest Class Doc Comment
 *
 * @category Class
 * @package  d2r_connectors\conficio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoiceDetailApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for invoiceDetailSubmit
     *
     * Submit an invoice detail (transaction).  Send AFTER corresponding invoice record.
     *
     */
    public function testInvoiceDetailSubmit()
    {
    }

    /**
     * Test case for invoiceDetailTest
     *
     * Test an invoice detail record.
     *
     */
    public function testInvoiceDetailTest()
    {
    }
}
