<?php
/**
 * TransactionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  d2r_connectors\conficio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * PartnerExchangeApi
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace d2r_connectors\conficio;

use \d2r_connectors\conficio\Configuration;
use \d2r_connectors\conficio\ApiException;
use \d2r_connectors\conficio\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TransactionApiTest Class Doc Comment
 *
 * @category Class
 * @package  d2r_connectors\conficio
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TransactionApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for transactionPost
     *
     * Post a transaction (payment).
     *
     */
    public function testTransactionPost()
    {
    }

    /**
     * Test case for transactionTest
     *
     * Test a transaction record.
     *
     */
    public function testTransactionTest()
    {
    }
}
